---
title: "imdb"
author: "Robin Killewald"
date: "11/11/2021"
output: html_document
---

IMPORT PACKAGES & SET THEME
```{r}
# imports
require(data.table)
require(gridExtra)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(scales)
library(devtools)
library(GGally)
library(ggpubr)
library(ggthemr)
library(treemapify)
library(viridis)
ggthemr('dust')
```

IMPORT IMDB
```{r}
# when downloaded all datasets from https://www.imdb.com/interfaces/ and renamed according to the follwing names, data can be imported via

# import original dbs
title_akas <- as.data.frame(fread("data_original/title_akas.tsv"))
title_basics <- as.data.frame(fread("data_original/title_basics.tsv"))
title_crew <- as.data.frame(fread("data_original/title_crew.tsv"))
title_episode <- as.data.frame(fread("data_original/title_episode.tsv"))
title_principals <- as.data.frame(fread("data_original/title_principals.tsv"))
title_ratings <- as.data.frame(fread("data_original/title_ratings.tsv"))
name_basics <- as.data.frame(fread("data_original/name_basics.tsv"))
```

REDUCE DB
```{r}
# reduce dbs
red_title_akas <- title_akas[1:000,]
red_title_basics <- title_basics[1:100000,]
red_title_crew <- title_crew[1:3000,]
red_title_episode <- title_episode[1:3000,]
red_title_principals <- title_principals[1:3000,]
red_title_ratings <- title_ratings[1:100000,]
red_name_basics <- name_basics[1:3000,]
```

EXPORT REDUCED IMDB
```{r}
# export reduced dbs
write.csv(title_akas_reduced, "data_reduced/title_akas_reduced.csv", row.names = FALSE)
write.csv(title_basics_reduced, "data_reduced/title_basics_reduced.csv", row.names = FALSE)
write.csv(title_crew_reduced, "data_reduced/title_crew_reduced.csv", row.names = FALSE)
write.csv(title_episode_reduced, "data_reduced/title_episode_reduced.csv", row.names = FALSE)
write.csv(title_principals_reduced, "data_reduced/title_principals_reduced.csv", row.names = FALSE)
write.csv(title_ratings_reduced, "data_reduced/title_ratings_reduced.csv", row.names = FALSE)
write.csv(name_basics_reduced, "data_reduced/name_basics_reduced.csv", row.names = FALSE)
```

IMPORT REDUCED IMDB
```{r}
# import reduced dbs
red_title_akas <- read.csv2("data_reduced/title_akas.csv", sep = ",")
red_title_basics <- read.csv2("data_reduced/title_basics.csv", sep = ",")
red_title_crew <- read.csv2("data_reduced/title_crew.csv", sep = ",")
red_title_episode <- read.csv2("data_reduced/title_episode.csv", sep = ",")
red_title_principals <- read.csv2("data_reduced/title_principals.csv", sep = ",")
red_title_ratings <- read.csv2("data_reduced/title_ratings.csv", sep = ",")
red_name_basics <- read.csv2("data_reduced/name_basics.csv", sep = ",")
```

FIGURE 3
```{r}
# plot number of films per year

# filter out oldest titles as they distract
new_titles <- title_basics %>%
  filter(between(startYear, 1900, 2021))
new_titles$startYear = as.integer(new_titles$startYear)

# plot the titles per year
ggplot(data = new_titles, mapping = aes(x = startYear)) +
  geom_bar() +
  scale_y_continuous(labels = unit_format(unit = "K", scale = 1e-3)) +
  labs(x = "Year", y = "Number of Titles")

ggsave("titles_per_year.pdf", width = 8, height = 4)

# how many titles exist in 2018?
titles_2018 <- nrow(title_basics %>% filter( startYear == 2018))
```

FIGURE 4
```{r}
# get 10 best voted titles 
basics_ratings <- merge(x = title_basics, y = title_ratings, by = "tconst", all.x = TRUE)

# sort for avg rating, then for number of votes and add constraint of min 25k votes
# select only the nessary columns
sorted <- basics_ratings %>%
  arrange(desc(averageRating), desc(numVotes)) %>%
  filter(titleType == "movie", numVotes > 25000) %>%
  select(originalTitle, startYear, averageRating, numVotes)

# prepare data
sorted_s <- sorted[c(1:10),]
sorted_s <- cbind(c(1:10), sorted_s)
colnames(sorted_s) <- c("", "Title", "Year", "Rating", "Votes")

# plot table
ggtexttable(sorted_s, rows = NULL, 
            theme = ttheme(colnames.style = colnames_style(color = "black", fill = "#FAF7F3"),
                           tbody.style = tbody_style(color = "black", fill = "#FAF7F3"))) %>%
              tab_add_hline(at.row = 1:2, row.side = "top", linewidth = 2)

ggsave("best.pdf", width = 8, height = 6)
```

FIGURE 5
```{r}
# plot four dimensions of earliest movies
till1893 <- basics_ratings %>%
  filter(between(startYear, 1874, 1893))

# clean data
till1893$startYear = as.integer(till1894$startYear)

# plot the different dimensions via geom_point
ggplot(till1893, aes(x = startYear, y = averageRating, size = numVotes, color = genres)) +
  geom_point() +
  labs(x = "Year", y = "Rating (avg)", size = "Number of votes", color = "Genres")

ggsave("first_movies.pdf", width = 8, height = 4)
```

FIGURE 6
```{r}
# filter for titles from 1970
only1970 <- title_basics %>%
  filter(startYear == 1970)

# merge titles with their genres and make them numerical
tbr <- merge(x = only1970, y = title_ratings, by = "tconst", all.x = TRUE)
tbr$averageRating = as.numeric(tbr$averageRating)

# drop unnessecary columns and rows without rating
tbr <- tbr[, c("genres","averageRating", "numVotes")]
tbr <- tbr %>% drop_na(averageRating)

# if titles has multiple genres, copy entry per genre
for (i in c(1:nrow(tbr))) {
  if(grepl(",", tbr$genres[i])) {
    current_genres <- unlist(strsplit(tbr$genres[i], ","))
    tbr$genres[i] <- current_genres[1]
    for (j in c(2:length(current_genres))) {
      tbr <- rbind(tbr, tbr[i,])
      tbr$genres[nrow(tbr)] <- current_genres[j]
    }
  }
}

# prepare deviation from average
tbr_avg_deviation <- tbr %>% 
  group_by(genres) %>% 
  summarise(
    mean_p_g = mean(averageRating),
    total_votes = sum(numVotes)
            ) %>% 
  mutate(
    genres = reorder(genres, mean_p_g),
    deviation = mean_p_g - mean(mean_p_g)
  ) %>%
  filter(total_votes > 120000)

# prepare most voted genres for bar chart
tbr_regular_bar <- tbr_avg_deviation %>%
  arrange(desc(total_votes)) %>%
  top_n(5)

# plot regular bar chart
ggplot(data = tbr_regular_bar, mapping = aes(x = genres, y=mean_p_g)) +
  geom_bar(stat = "identity") +
  labs(x = "Genre", y = "Mean rating") +
  coord_cartesian(ylim=c(6.8, 7.1))

ggsave("reg_bar.pdf", width = 4, height = 3)

# plot deviation from average
ggplot(data = tbr_avg_deviation) +
  geom_col(mapping = aes(x = genres, y = deviation)) +
  coord_flip() +
  labs(x = "Genre", y = "Deviation from the mean rating of all titles")

ggsave("div_bar.pdf", width = 4, height = 3)

#p <- grid.arrange(p1, p2, ncol=2)
```

FIGURE 7
```{r}
# prepare professions
professions <- title_principals %>%
  count(category) %>%
  filter(!grepl("self", category))%>%
  filter(!grepl("archive_sound", category))%>%
  filter(!grepl("archive_footage", category))

# merge actors and actress as gender is not relevant here
professions[1,2] = professions[1,2] + professions[2,2]
professions <- professions %>%
  filter(category != "actress") %>%
  arrange(desc(n)) %>%
  rename("Profession" = "category")
professions[1,1] = "actor / actress"

# plot pie chart
ggplot(data = professions, aes(x="", y=n, fill=Profession)) +
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y") +
  theme_void()

ggsave("pie.pdf", width = 4, height = 3)

# plot treemap
ggplot(data = professions, mapping = aes(area = n, fill = Profession, label = Profession)) +
  geom_treemap()+
  theme(legend.position = "none")

ggsave("treemap.pdf", width = 4, height = 3)
```

FIGURE 8
```{r}
# convert numbers to numerics to be able to calculate with them
title_basics$startYear = as.numeric(title_basics$startYear)
title_basics$endYear = as.numeric(title_basics$endYear)
title_basics$runtimeMinutes = as.numeric(title_basics$runtimeMinutes)

# drop NA's and calcualte duration (staring and ending in the same year ends in a one year duration)
series <- title_basics %>%
  drop_na(startYear, endYear) %>%
  mutate(duration = endYear - startYear + 1)

# plot time series of runtime in minutes
ggplot(data = series, mapping = aes(x = startYear, y = runtimeMinutes)) +
  geom_point(alpha = 0.2) +
  facet_grid(cols = vars(titleType)) +
  scale_y_continuous(trans='log2') +
  labs(x = "Year of release", y = "Runtime in minutes")

ggsave("ts_min.pdf", width = 8, height = 4)

# plot time series of duration in years
ggplot(data = series, mapping = aes(x = startYear, y = duration)) +
  geom_point(alpha = 0.2) +
  facet_grid(cols = vars(titleType)) +
  labs(x = "Year of release", y = "Duration in years")

ggsave("ts_dur.pdf", width = 8, height = 4)

#scale_colour_gradient(low = "burlywood", high = "brown", na.value = NA)
```

TEST PLAYGROUND
```{r}
merged_title_basics_crew <- merge(x = red_title_basics, y = red_title_crew, by = "tconst", all.x = TRUE)
merged_title_basics_crew_episode <- merge(x = merged_title_basics_crew, y = red_title_episode, by = "tconst", all.x = TRUE)
merged_title_basics_crew_episode_ratings <- merge(x = merged_title_basics_crew_episode, y = red_title_ratings, by = "tconst", all.x = TRUE)

title_basics %>% filter(originalTitle == "Suits")
title_episode %>% filter(parentTconst == "tt1632701")
title_basics %>% filter(tconst == "tt1976882")#episode
title_ratings %>% filter(tconst == "tt1632701")
title_ratings %>% filter(tconst == "tt1976882")
```